### PR TITLE
added name to about

### PR DESCRIPTION
**Pull request by emma-mp**

### CODE REVIEW

**Review by gabrielsessions — CHANGES_REQUESTED** [review]
Good job! The only change I'd like for you to make is to exclude the backend/node_modules folder from your PR. I'll send a Slack message about this soon!

**Comment by emma-mp** [comment]
I think I may have fixed it? but I was having some weird issues with trying to get the updates from main into my branch so let me know if something still seems off. It says 200+ files changed at the top of this PR, but when I go into my most recent commit it just says 11 files, which I think is correct? Hopefully :)

**Review by gabrielsessions — APPROVED** [review]
I had to delete node_modules off of your branch. It looks like you can't retroactively remove the node_modules using .gitignore.
If you need to reinitialize node_modules on your local environment, run `npm install`.
Hopefully the .gitignore should prevent you from pushing node_modules in the future.

Thanks revising your .gitigonore!

**Comment by emma-mp** [comment]
yay okay thank you!

**Pull request merged**
